### MLB ENDPOINTS
###
# @name MLB Daily Scoreboard 
GET {{host}}/MLBTracker/Scoreboard

> {%
  client.test("Request executed successfully", function() {
      client.assert(response.status === 200 || response.status === 204)
  });
%}

###
# @name MLB Weekly Scoreboard
GET {{host}}/MLBTracker/WeeklyScoreboard

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 204)
    });
%}

### NBA ENDPOINTS
###
# @name NBA Daily Scoreboard
GET {{host}}/NBATracker/Scoreboard

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 204)
    });
%}

###
# @name NBA Weekly Scoreboard
GET {{host}}/NBATracker/WeeklyScoreboard

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 204)
    });
%}

### NCAA FOOTBALL ENDPOINTS
###
# @name NCAA Football Daily Scoreboard
GET {{host}}/NCAAFootballTracker/Scoreboard

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 204)
    });
%}
###
# @name NCAA Football Weekly Scoreboard
GET {{host}}/NCAAFootballTracker/WeeklyScoreboard

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 204)
    });
%}

### NFL ENDPOINTS
###
# @name NFL Daily Scoreboard
GET {{host}}/NFLTracker/Scoreboard

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 204)
    });
%}
###
# @name NFL Weekly Scoreboard
GET {{host}}/NFLTracker/WeeklyScoreboard

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 204)
    });
%}

### NHL ENDPOINTS
###
# @name NHL Daily Scoreboard
GET {{host}}/NHLTracker/Scoreboard

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 204)
    });
%}

###
# @name NHL Weekly Scoreboard
GET {{host}}/NHLTracker/WeeklyScoreboard

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200 || response.status === 204)
    });
%}
