### MLB ENDPOINTS
###
GET http://localhost:5005/api/MLBTracker/Scoreboard

###
GET http://localhost:5005/api/MLBTracker/WeeklyScoreboard



### NBA ENDPOINTS
###
GET http://localhost:5005/api/NBATracker



### NCAA FOOTBALL ENDPOINTS
###
GET http://localhost:5005/api/NCAAFootballTracker



### NFL ENDPOINTS
###
GET http://localhost:5005/api/NFLTracker/Scoreboard

###
GET http://localhost:5005/api/NFLTracker/WeeklyScoreboard



### NHL ENDPOINTS
###
GET http://localhost:5005/api/NHLTracker

