###
GET http://localhost:8080/api/MLBTracker

###
GET http://localhost:8080/api/NBATracker

###
GET http://localhost:8080/api/NCAAFootballTracker

###
GET http://localhost:8080/api/NFLTracker

###
GET http://localhost:8080/api/NHLTracker